export const ROUTES = {
  TERMS: '/terms',
  IMPRINT: '/imprint',
};

export const SUGGESTIONS = {
  '🍆': 'Aubergine',
  '🥦': 'Broccoli',
  '🫑': 'Peppers',
  '🥕': 'Carrots',
  '🥔': 'Potatoes',
  '🥩': 'Beef',
  '🍗': 'Chicken',
  '🍋': 'Lemons',
  '🍊': 'Oranges',
  '🥒': 'Cucumbers',
  '🐟': 'Fish',
  '🦐': 'Shrimp',
  '🦑': 'Squid',
  '🐷': 'Pork',
  '🥓': 'Bacon',
  '🥫': 'Canned tomatoes',
  '🫘': 'Beans',
  '🍎': 'Apples',
  '🍓': 'Strawberries',
  '🥭': 'Mangoes',
  '🥥': 'Coconut',
  '🍍': 'Pineapple',
  '🥬': 'Lettuce',
  '🫒': 'Olives',
  '🥚': 'Eggs',
};
